{% set name = "xarray-schema" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray-schema-{{ version }}.tar.gz
  sha256: 9c6c760489c0690a70394b2ad1368b32f8fa1333911c361b4adf249384212920

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=30.3.0
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - xarray >=0.16
    - numpy >=1.20

test:
  imports:
    - xarray_schema
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/carbonplan/xarray-schema
  summary: Schema validation for Xarray objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhamman
